### PR TITLE
One more test for TRY block

### PR DESCRIPTION
**Pull request by acheshkov**
- one more test
- package dependency changed

### CODE REVIEW

**Comment by acheshkov** [comment]
@lyriccoder this PR will pass tests after merge of https://github.com/acheshkov/program-graphs/pull/15

**Comment by lyriccoder** [comment]
let me check one thing

**Comment by lyriccoder** [comment]
Aah, I stil  see a similar bug, but with finally:
Here is the code:

```
from program_graphs.adg import parse_java
from slicing.block.block import gen_block_slices

java_code = '''
    try(FileWriter writer = new FileWriter(GlobalEnvironment.getInstance().result)) {
        Gson gson = new GsonBuilder().setPrettyPrinting();
        gson.toJson(smellResults, writer);
        writer.flush();
        if (Files.notExists(Paths.get(GlobalEnvironment.getInstance().result))) {
            FileUtils.copyFile(new File(Paths.get(GlobalEnvironment.getInstance().result)));
        }
    }
    finally {
        run3();
    }
    if (cmd.hasOptions("offline")) {
        run();
    }
    run1();
'''

adg = parse_java(java_code)
for block_sc in gen_block_slices(adg, java_code):
    print('######################################')
    print('Lines: ', block_sc.line_range[0][0],block_sc.line_range[1][0])
    print('\n'.join(java_code.split('\n')[block_sc.line_range[0][0]:block_sc.line_range[1][0]+1]))
```

It shows me wrong lines:
```
######################################
Lines:  10 14
        run3();
    }
    if (cmd.hasOptions("offline")) {
        run();
    }
######################################
Lines:  10 14
        run3();
    }
    if (cmd.hasOptions("offline")) {
        run();
    }
######################################
Lines:  10 15
        run3();
    }
    if (cmd.hasOptions("offline")) {
        run();
    }
    run1();
######################################
Lines:  2 11
        Gson gson = new GsonBuilder().setPrettyPrinting();
        gson.toJson(smellResults, writer);
        writer.flush();
        if (Files.notExists(Paths.get(GlobalEnvironment.getInstance().result))) {
            FileUtils.copyFile(new File(Paths.get(GlobalEnvironment.getInstance().result)));
        }
    }
    finally {
        run3();
    }
######################################
Lines:  2 14
        Gson gson = new GsonBuilder().setPrettyPrinting();
        gson.toJson(smellResults, writer);
        writer.flush();
        if (Files.notExists(Paths.get(GlobalEnvironment.getInstance().result))) {
            FileUtils.copyFile(new File(Paths.get(GlobalEnvironment.getInstance().result)));
        }
    }
    finally {
        run3();
    }
    if (cmd.hasOptions("offline")) {
        run();
    }
######################################
Lines:  2 15
        Gson gson = new GsonBuilder().setPrettyPrinting();
        gson.toJson(smellResults, writer);
        writer.flush();
        if (Files.notExists(Paths.get(GlobalEnvironment.getInstance().result))) {
            FileUtils.copyFile(new File(Paths.get(GlobalEnvironment.getInstance().result)));
        }
    }
    finally {
        run3();
    }
    if (cmd.hasOptions("offline")) {
        run();
    }
    run1();
######################################
Lines:  5 11
        if (Files.notExists(Paths.get(GlobalEnvironment.getInstance().result))) {
            FileUtils.copyFile(new File(Paths.get(GlobalEnvironment.getInstance().result)));
        }
    }
    finally {
        run3();
    }
######################################
Lines:  5 14
        if (Files.notExists(Paths.get(GlobalEnvironment.getInstance().result))) {
            FileUtils.copyFile(new File(Paths.get(GlobalEnvironment.getInstance().result)));
        }
    }
    finally {
        run3();
    }
    if (cmd.hasOptions("offline")) {
        run();
    }
######################################
Lines:  5 15
        if (Files.notExists(Paths.get(GlobalEnvironment.getInstance().result))) {
            FileUtils.copyFile(new File(Paths.get(GlobalEnvironment.getInstance().result)));
        }
    }
    finally {
        run3();
    }
    if (cmd.hasOptions("offline")) {
        run();
    }
    run1();
######################################

```

**Review by lyriccoder — APPROVED** [review]
ok

**Pull request merged**
