### PR TITLE
Performance testing with GitHub actions

### PR DESCRIPTION
**Pull request by lyriccoder**
The current github flow counts the time (mean value) of slice generation for 37 files:
1) for the current implementation
2) for the previous merge to master

Then ttest (one tailed) is performed to check whether the mean of 1) is equal to 2).
If current implementation is slower than the previous implementation (previous latest merge to master), it raises an exception

### CODE REVIEW

**Comment by lyriccoder** [comment]
| Filename | Mean previous | Mean current | Diff | | ------------ | ----------------- | ---------------- | -------- | | CPPParser.java | 0.04438 | 0.04324 | -0.00114 | | SimpleMapGenerator.java | 0.05334 | 0.05231 | -0.00103 | | TriMeshBeveler.java | 0.07304 | 0.07218 | -0.00086 | | ULocale.java | 0.044 | 0.0435 | -0.00049 | | LocalCorrectionsSubProcessor.java | 0.06912 | 0.06817 | -0.00095 | | 200ncss.java | 0.07698 | 0.07703 | 4e-05 | | 150ncss.java | 0.04159 | 0.04166 | 7e-05 | | Main_run.java | 0.01903 | 0.01899 | -5e-05 | | PreferenceConstants.java | 0.05553 | 0.05615 | 0.00063 | | Product.java | 0.00263 | 0.00265 | 2e-05 | | Expression.java | 0.05326 | 0.0541 | 0.00085 | | RDResumeHandler.java | 0.06774 | 0.07032 | +0.00258 | | GroupManager.java | 0.06057 | 0.06245 | +0.00188 | | TheOriginalJDTParserClass.java | 0.02858 | 0.02937 | 0.00079 | | ReportColonyPanel.java | 0.05847 | 0.05968 | 0.00121 | | PcmlData.java | 0.06238 | 0.0625 | 0.00012 | | PreserveAspectRatioParser.java | 0.0403 | 0.0393 | -0.001 | | UnicodeSet.java | 0.00084 | 0.00085 | 0.0 | | Main.java | 0.12316 | 0.12237 | -0.0008 | | MapViewer.java | 0.06783 | 0.067 | -0.00083 | | FindUnrelatedTypesInGenericContainer.java | 0.04966 | 0.04869 | -0.00097 | | ParserDDL.java | 0.03157 | 0.03124 | -0.00033 | | DiskManagerRandomReadController.java | 0.05827 | 0.05772 | -0.00054 | | User.java | 0.10744 | 0.10886 | 0.00142 | | QuickFixProcessor.java | 0.04644 | 0.04731 | 0.00087 | | SybaseASE15Dialect.java | 0.01575 | 0.01568 | -8e-05 | | DocCommentParser.java | 0.04376 | 0.04352 | -0.00025 | | MemberFactory.java | 0.05678 | 0.05631 | -0.00047 | | VPayment.java | 0.04982 | 0.05019 | 0.00037 | | LexGen.java | 0.0536 | 0.05356 | -4e-05 | | AbstractCommentParser.java | 0.06751 | 0.06809 | 0.00058 | | ConfigSectionConnectionProxy.java | 0.06511 | 0.06531 | 0.0002 | | ObjectPropertiesDialog.java | 0.0292 | 0.02966 | 0.00047 | | ColonyPlan.java | 0.06441 | 0.06448 | 7e-05 | | CompletionEngine.java | 0.07084 | 0.07108 | 0.00024 | | CollationRuleParser.java | 0.07937 | 0.07999 | 0.00062 | | TryStatement.java | 0.04967 | 0.04939 | -0.00029 |

**Comment by lyriccoder** [comment]
| Filename | Mean previous | Mean current | Diff | Pvalue | Power | Var previous | Var current | Cohen-d | Number of observations | Ttest 
| ------------ | ----------------- | ---------------- | -------- | ----------------- | ----------------- | ----------------- | ----------------- | ----------------- | ----------------- | ----------------- |
|  150ncss.java  |  0.10263  |   0.06908  |    <span style="color:green">-0.03355</span> |     1.0 |    0.0  |  0.0002894677  |   0.0001333245  |    2.30174 |   3  |  :white_check_mark   |
|  200ncss.java  |  0.19819  |   0.13178  |    <span style="color:green">-0.06641</span> |     1.0 |    0.0  |  0.0010103736  |   0.0004118268  |    2.48414 |   2  |  :white_check_mark   |
|  AbstractCommentParser.java  |  0.17918  |   0.11929  |    <span style="color:green">-0.05988</span> |     1.0 |    0.0  |  0.0009493497  |   0.0004232532  |    2.28013 |   3  |  :white_check_mark   |
|  CollationRuleParser.java  |  0.20985  |   0.1478  |    <span style="color:green">-0.06205</span> |     1.0 |    0.0  |  0.0013262309  |   0.0004132634  |    2.09878 |   3  |  :white_check_mark   |
|  ColonyPlan.java  |  0.16829  |   0.12083  |    <span style="color:green">-0.04746</span> |     1.0 |    0.0  |  0.0009082748  |   0.0002718761  |    1.94885 |   4  |  :white_check_mark   |
|  CompletionEngine.java  |  0.19293  |   0.13834  |    <span style="color:green">-0.05459</span> |     1.0 |    0.0  |  0.0007942108  |   0.000206962  |    2.43387 |   3  |  :white_check_mark   |
|  ConfigSectionConnectionProxy.java  |  0.17394  |   0.12716  |    <span style="color:green">-0.04678</span> |     1.0 |    0.0  |  0.0003361207  |   0.0001183751  |    3.09533 |   2  |  :white_check_mark   |
|  CPPParser.java  |  0.10827  |   0.0747  |    <span style="color:green">-0.03357</span> |     1.0 |    0.0  |  0.0007317445  |   0.0002951331  |    1.47779 |   6  |  :white_check_mark   |
|  DiskManagerRandomReadController.java  |  0.16807  |   0.10694  |    <span style="color:green">-0.06113</span> |     1.0 |    0.0  |  0.0032618371  |   0.0002472426  |    1.45576 |   6  |  :white_check_mark   |
|  DocCommentParser.java  |  0.11148  |   0.07688  |    <span style="color:green">-0.0346</span> |     1.0 |    0.0  |  0.0006165648  |   0.0002582862  |    1.65024 |   5  |  :white_check_mark   |
|  Expression.java  |  0.13877  |   0.09425  |    <span style="color:green">-0.04451</span> |     1.0 |    0.0  |  0.0005485608  |   0.0002562351  |    2.21341 |   3  |  :white_check_mark   |
|  FindUnrelatedTypesInGenericContainer.java  |  0.13207  |   0.09012  |    <span style="color:green">-0.04195</span> |     1.0 |    0.0  |  0.0004749621  |   0.0002087282  |    2.26342 |   3  |  :white_check_mark   |
|  GroupManager.java  |  0.16222  |   0.11411  |    <span style="color:green">-0.0481</span> |     1.0 |    0.0  |  0.0006243527  |   0.0002222799  |    2.33218 |   3  |  :white_check_mark   |
|  LexGen.java  |  0.14465  |   0.10084  |    <span style="color:green">-0.04381</span> |     1.0 |    0.0  |  0.0006852131  |   0.0002223038  |    2.05146 |   3  |  :white_check_mark   |
|  LocalCorrectionsSubProcessor.java  |  0.1835  |   0.12913  |    <span style="color:green">-0.05437</span> |     1.0 |    0.0  |  0.0007357499  |   0.0002416276  |    2.45332 |   3  |  :white_check_mark   |
|  Main.java  |  0.31624  |   0.22983  |    <span style="color:green">-0.08641</span> |     1.0 |    0.0  |  0.0010638744  |   0.000537384  |    3.04613 |   2  |  :white_check_mark   |
|  Main_run.java  |  0.05342  |   0.03686  |    <span style="color:green">-0.01656</span> |     1.0 |    0.0  |  6.27954e-05  |   3.75142e-05  |    2.33247 |   3  |  :white_check_mark   |
|  MapViewer.java  |  0.19152  |   0.1527  |    <span style="color:green">-0.03882</span> |     1.0 |    0.0  |  0.0005134502  |   0.0089388988  |    0.56328 |   39  |  :white_check_mark   |
|  MemberFactory.java  |  0.15967  |   0.11043  |    <span style="color:green">-0.04924</span> |     1.0 |    0.0  |  0.0005614023  |   0.0004876878  |    2.14459 |   3  |  :white_check_mark   |
|  ObjectPropertiesDialog.java  |  0.08601  |   0.05632  |    <span style="color:green">-0.02968</span> |     1.0 |    0.0  |  0.0002358754  |   0.0001011781  |    2.28086 |   3  |  :white_check_mark   |
|  ParserDDL.java  |  0.08831  |   0.05764  |    <span style="color:green">-0.03066</span> |     1.0 |    0.0  |  0.0003490371  |   0.0001346227  |    1.96688 |   4  |  :white_check_mark   |
|  PcmlData.java  |  0.17786  |   0.11824  |    <span style="color:green">-0.05962</span> |     1.0 |    0.0  |  0.0009026377  |   0.0003327675  |    2.39291 |   3  |  :white_check_mark   |
|  PreferenceConstants.java  |  0.14626  |   0.10287  |    <span style="color:green">-0.04338</span> |     1.0 |    0.0  |  0.0005771497  |   0.0001954651  |    2.20169 |   3  |  :white_check_mark   |
|  PreserveAspectRatioParser.java  |  0.09964  |   0.06918  |    <span style="color:green">-0.03046</span> |     1.0 |    0.0  |  0.0004050004  |   0.0001369037  |    1.84587 |   4  |  :white_check_mark   |
|  Product.java  |  0.00467  |   0.00369  |    <span style="color:green">-0.00098</span> |     1.0 |    0.0  |  2.3402e-06  |   1.162e-07  |    0.88299 |   16  |  :white_check_mark   |
|  QuickFixProcessor.java  |  0.11442  |   0.0782  |    <span style="color:green">-0.03622</span> |     1.0 |    0.0  |  0.0007063138  |   0.000314206  |    1.59941 |   5  |  :white_check_mark   |
|  RDResumeHandler.java  |  0.2038  |   0.12696  |    <span style="color:green">-0.07684</span> |     1.0 |    0.0  |  0.0046721297  |   0.0003312732  |    1.53249 |   6  |  :white_check_mark   |
|  ReportColonyPanel.java  |  0.18529  |   0.14693  |    <span style="color:green">-0.03836</span> |     1.0 |    0.0  |  0.0072231644  |   0.0012144706  |    0.5891 |   36  |  :white_check_mark   |
|  SimpleMapGenerator.java  |  0.14783  |   0.1593  |    <span style="color:red">+0.01147</span> |     0.01399 |    0.71123  |  0.0006057344  |   0.0047802196  |    0.22056 |   254  |  &#9746;   |
|  SybaseASE15Dialect.java  |  0.04009  |   0.03062  |    <span style="color:green">-0.00947</span> |     1.0 |    0.0  |  0.0001194656  |   6.58433e-05  |    0.98174 |   13  |  :white_check_mark   |
|  TheOriginalJDTParserClass.java  |  0.07334  |   0.05024  |    <span style="color:green">-0.0231</span> |     1.0 |    0.0  |  0.0004579699  |   0.0001591374  |    1.31199 |   7  |  :white_check_mark   |
|  TriMeshBeveler.java  |  0.19965  |   0.13756  |    <span style="color:green">-0.06209</span> |     1.0 |    0.0  |  0.0009816282  |   0.0003004609  |    2.44605 |   3  |  :white_check_mark   |
|  TryStatement.java  |  0.13027  |   0.09031  |    <span style="color:green">-0.03997</span> |     1.0 |    0.0  |  0.0006201314  |   0.0002257321  |    1.93856 |   4  |  :white_check_mark   |
|  ULocale.java  |  0.12798  |   0.07983  |    <span style="color:green">-0.04815</span> |     1.0 |    0.0  |  0.0046365029  |   0.0002052152  |    0.97621 |   13  |  :white_check_mark   |
|  UnicodeSet.java  |  0.00153  |   0.00029  |    <span style="color:green">-0.00124</span> |     1.0 |    0.0  |  4.7689e-06  |   1.194e-07  |    0.79369 |   20  |  :white_check_mark   |
|  User.java  |  0.30254  |   0.21825  |    <span style="color:green">-0.08429</span> |     1.0 |    0.0  |  0.0017428741  |   0.0003925647  |    2.57299 |   2  |  :white_check_mark   |
|  VPayment.java  |  0.13085  |   0.0908  |    <span style="color:green">-0.04004</span> |     1.0 |    0.0  |  0.0005595854  |   0.0001934823  |    2.05853 |   3  |  :white_check_mark   |

**Comment by lyriccoder** [comment]
prev

| Filename | Mean previous | Mean current | Diff | Pvalue | Power | Var previous | Var current | Cohen-d | Number of observations
| ------------ | ----------------- | ---------------- | -------- | ----------------- | ----------------- | ----------------- | ----------------- | ----------------- | ----------------- |
|  150ncss.java  |  0.02599  |   0.02531  |    <span style="color:green">-0.00068</span> |     0.94779 |    0.00054  |  1.79065e-05  |   1.71929e-05  |    0.16275 |   467  |
|  200ncss.java  |  0.04976  |   0.04783  |    <span style="color:green">-0.00194</span> |     0.99425 |    1e-05  |  6.25017e-05  |   5.31072e-05  |    0.2539 |   192  |
|  AbstractCommentParser.java  |  0.04503  |   0.04334  |    <span style="color:green">-0.00169</span> |     0.98718 |    5e-05  |  5.87267e-05  |   5.45807e-05  |    0.22402 |   247  |
|  CollationRuleParser.java  |  0.05266  |   0.05358  |    0.00092 |     0.13348 |    0.29629  |  8.20406e-05  |   5.32925e-05  |    0.11116 |   1001  |
|  ColonyPlan.java  |  0.04232  |   0.04389  |    <span style="color:red">+0.00157</span> |     0.0105 |    0.74809  |  5.61858e-05  |   3.50599e-05  |    0.23173 |   230  |
|  CompletionEngine.java  |  0.04845  |   0.05018  |    <span style="color:red">+0.00173</span> |     0.00268 |    0.87487  |  4.91298e-05  |   2.66888e-05  |    0.27993 |   158  |
|  ConfigSectionConnectionProxy.java  |  0.04373  |   0.04617  |    <span style="color:red">+0.00244</span> |     0.0 |    1.0  |  2.07924e-05  |   1.52651e-05  |    0.5726 |   38  |
|  CPPParser.java  |  0.0274  |   0.02733  |    <span style="color:green">-7e-05</span> |     0.54207 |    0.04002  |  4.52657e-05  |   3.8059e-05  |    0.01057 |   110614  |
|  DiskManagerRandomReadController.java  |  0.04227  |   0.03891  |    <span style="color:green">-0.00336</span> |     0.99898 |    0.0  |  0.0002017771  |   3.18832e-05  |    0.31048 |   128  |
|  DocCommentParser.java  |  0.0282  |   0.02811  |    <span style="color:green">-8e-05</span> |     0.55565 |    0.03716  |  3.81407e-05  |   3.33074e-05  |    0.01401 |   63042  |
|  Expression.java  |  0.03498  |   0.03435  |    <span style="color:green">-0.00063</span> |     0.86139 |    0.00316  |  3.39339e-05  |   3.30429e-05  |    0.10881 |   1045  |
|  FindUnrelatedTypesInGenericContainer.java  |  0.03332  |   0.03287  |    <span style="color:green">-0.00045</span> |     0.80164 |    0.00635  |  2.93811e-05  |   2.69166e-05  |    0.08484 |   1718  |
|  GroupManager.java  |  0.04081  |   0.04148  |    0.00067 |     0.12576 |    0.30908  |  3.86224e-05  |   2.86642e-05  |    0.11484 |   938  |
|  LexGen.java  |  0.03644  |   0.03672  |    0.00027 |     0.32527 |    0.11658  |  4.23872e-05  |   2.86672e-05  |    0.04533 |   6017  |
|  LocalCorrectionsSubProcessor.java  |  0.04611  |   0.04688  |    0.00077 |     0.10859 |    0.34055  |  4.55134e-05  |   3.11591e-05  |    0.1236 |   810  |
|  Main.java  |  0.07912  |   0.08304  |    <span style="color:red">+0.00391</span> |     0.0 |    0.99902  |  6.58112e-05  |   6.92985e-05  |    0.47504 |   55  |
|  Main_run.java  |  0.01375  |   0.01374  |    <span style="color:green">-1e-05</span> |     0.52783 |    0.04321  |  3.8845e-06  |   4.8377e-06  |    0.00699 |   253356  |
|  MapViewer.java  |  0.0481  |   0.05534  |    <span style="color:red">+0.00724</span> |     0.0016 |    0.90593  |  3.1762e-05  |   0.0011527182  |    0.2966 |   141  |
|  MemberFactory.java  |  0.04018  |   0.04016  |    <span style="color:green">-2e-05</span> |     0.51225 |    0.04691  |  3.47283e-05  |   6.28899e-05  |    0.00307 |   1308641  |
|  ObjectPropertiesDialog.java  |  0.02186  |   0.02073  |    <span style="color:green">-0.00113</span> |     0.99871 |    0.0  |  1.45912e-05  |   1.30475e-05  |    0.30328 |   135  |
|  ParserDDL.java  |  0.02243  |   0.0212  |    <span style="color:green">-0.00123</span> |     0.99712 |    1e-05  |  2.15914e-05  |   1.73603e-05  |    0.27761 |   161  |
|  PcmlData.java  |  0.04471  |   0.04296  |    <span style="color:green">-0.00174</span> |     0.99307 |    2e-05  |  5.58371e-05  |   4.29121e-05  |    0.24718 |   203  |
|  PreferenceConstants.java  |  0.03684  |   0.03745  |    0.0006 |     0.13886 |    0.28782  |  3.57024e-05  |   2.52063e-05  |    0.10869 |   1047  |
|  PreserveAspectRatioParser.java  |  0.02525  |   0.02534  |    0.0001 |     0.41856 |    0.07501  |  2.50533e-05  |   1.76545e-05  |    0.02057 |   29219  |
|  Product.java  |  0.00163  |   0.00183  |    <span style="color:red">+0.0002</span> |     0.0 |    1.0  |  1.448e-07  |   1.5e-08  |    0.70211 |   25  |
|  QuickFixProcessor.java  |  0.02893  |   0.02859  |    <span style="color:green">-0.00034</span> |     0.69946 |    0.01511  |  4.36925e-05  |   4.05185e-05  |    0.05233 |   4516  |
|  RDResumeHandler.java  |  0.05116  |   0.04609  |    <span style="color:green">-0.00506</span> |     0.99995 |    0.0  |  0.0002890177  |   4.27194e-05  |    0.39207 |   81  |
|  ReportColonyPanel.java  |  0.04655  |   0.05326  |    <span style="color:red">+0.00671</span> |     7e-05 |    0.98623  |  0.0004468245  |   0.0001566124  |    0.38553 |   83  |
|  SimpleMapGenerator.java  |  0.03723  |   0.05771  |    <span style="color:red">+0.02047</span> |     0.0 |    1.0  |  3.74707e-05  |   0.0006164346  |    1.12946 |   10  |
|  SybaseASE15Dialect.java  |  0.01044  |   0.0115  |    <span style="color:red">+0.00106</span> |     0.0001 |    0.98201  |  7.3901e-06  |   8.4908e-06  |    0.37485 |   88  |
|  TheOriginalJDTParserClass.java  |  0.01871  |   0.01854  |    <span style="color:green">-0.00017</span> |     0.63082 |    0.02393  |  2.833e-05  |   2.05216e-05  |    0.03342 |   11068  |
|  TriMeshBeveler.java  |  0.05012  |   0.0499  |    <span style="color:green">-0.00022</span> |     0.62308 |    0.02511  |  6.07235e-05  |   3.8746e-05  |    0.03138 |   12557  |
|  TryStatement.java  |  0.03287  |   0.03293  |    6e-05 |     0.45658 |    0.06228  |  3.83613e-05  |   2.91093e-05  |    0.01091 |   103861  |
|  ULocale.java  |  0.0323  |   0.02917  |    <span style="color:green">-0.00313</span> |     0.99348 |    2e-05  |  0.0002868138  |   2.64636e-05  |    0.24939 |   199  |
|  UnicodeSet.java  |  0.00085  |   0.00061  |    <span style="color:green">-0.00024</span> |     1.0 |    0.0  |  2.95e-07  |   1.54e-08  |    0.61331 |   33  |
|  User.java  |  0.07571  |   0.07888  |    <span style="color:red">+0.00316</span> |     0.00022 |    0.97098  |  0.0001078141  |   5.06233e-05  |    0.35463 |   99  |
|  VPayment.java  |  0.03301  |   0.03311  |    0.0001 |     0.42841 |    0.07151  |  3.46159e-05  |   2.49506e-05  |    0.01805 |   37939  |

**Comment by lyriccoder** [comment]
| Filename | Mean previous | Mean current | Diff | Pvalue | Power | Var previous | Var current | Cohen-d | Number of observations | Ttest 
| ------------ | ----------------- | ---------------- | -------- | ----------------- | ----------------- | ----------------- | ----------------- | ----------------- | ----------------- | ----------------- |
|  150ncss.java  |  0.10263  |   0.06908  |    <span style="color:green">-0.03355</span> |     1.0 |    0.0  |  0.0002894677  |   0.0001333245  |    2.30174 |   3  |  &#10004;   |
|  200ncss.java  |  0.19819  |   0.13178  |    <span style="color:green">-0.06641</span> |     1.0 |    0.0  |  0.0010103736  |   0.0004118268  |    2.48414 |   2  |  &#10004;   |
|  AbstractCommentParser.java  |  0.17918  |   0.11929  |    <span style="color:green">-0.05988</span> |     1.0 |    0.0  |  0.0009493497  |   0.0004232532  |    2.28013 |   3  |  &#10004;   |
|  CollationRuleParser.java  |  0.20985  |   0.1478  |    <span style="color:green">-0.06205</span> |     1.0 |    0.0  |  0.0013262309  |   0.0004132634  |    2.09878 |   3  |  &#10004;   |
|  ColonyPlan.java  |  0.16829  |   0.12083  |    <span style="color:green">-0.04746</span> |     1.0 |    0.0  |  0.0009082748  |   0.0002718761  |    1.94885 |   4  |  &#10004;   |
|  CompletionEngine.java  |  0.19293  |   0.13834  |    <span style="color:green">-0.05459</span> |     1.0 |    0.0  |  0.0007942108  |   0.000206962  |    2.43387 |   3  |  &#10004;   |
|  ConfigSectionConnectionProxy.java  |  0.17394  |   0.12716  |    <span style="color:green">-0.04678</span> |     1.0 |    0.0  |  0.0003361207  |   0.0001183751  |    3.09533 |   2  |  &#10004;   |
|  CPPParser.java  |  0.10827  |   0.0747  |    <span style="color:green">-0.03357</span> |     1.0 |    0.0  |  0.0007317445  |   0.0002951331  |    1.47779 |   6  |  &#10004;   |
|  DiskManagerRandomReadController.java  |  0.16807  |   0.10694  |    <span style="color:green">-0.06113</span> |     1.0 |    0.0  |  0.0032618371  |   0.0002472426  |    1.45576 |   6  |  &#10004;   |
|  DocCommentParser.java  |  0.11148  |   0.07688  |    <span style="color:green">-0.0346</span> |     1.0 |    0.0  |  0.0006165648  |   0.0002582862  |    1.65024 |   5  |  &#10004;   |
|  Expression.java  |  0.13877  |   0.09425  |    <span style="color:green">-0.04451</span> |     1.0 |    0.0  |  0.0005485608  |   0.0002562351  |    2.21341 |   3  |  &#10004;   |
|  FindUnrelatedTypesInGenericContainer.java  |  0.13207  |   0.09012  |    <span style="color:green">-0.04195</span> |     1.0 |    0.0  |  0.0004749621  |   0.0002087282  |    2.26342 |   3  |  &#10004;   |
|  GroupManager.java  |  0.16222  |   0.11411  |    <span style="color:green">-0.0481</span> |     1.0 |    0.0  |  0.0006243527  |   0.0002222799  |    2.33218 |   3  |  &#10004;   |
|  LexGen.java  |  0.14465  |   0.10084  |    <span style="color:green">-0.04381</span> |     1.0 |    0.0  |  0.0006852131  |   0.0002223038  |    2.05146 |   3  |  &#10004;   |
|  LocalCorrectionsSubProcessor.java  |  0.1835  |   0.12913  |    <span style="color:green">-0.05437</span> |     1.0 |    0.0  |  0.0007357499  |   0.0002416276  |    2.45332 |   3  |  &#10004;   |
|  Main.java  |  0.31624  |   0.22983  |    <span style="color:green">-0.08641</span> |     1.0 |    0.0  |  0.0010638744  |   0.000537384  |    3.04613 |   2  |  &#10004;   |
|  Main_run.java  |  0.05342  |   0.03686  |    <span style="color:green">-0.01656</span> |     1.0 |    0.0  |  6.27954e-05  |   3.75142e-05  |    2.33247 |   3  |  &#10004;   |
|  MapViewer.java  |  0.19152  |   0.1527  |    <span style="color:green">-0.03882</span> |     1.0 |    0.0  |  0.0005134502  |   0.0089388988  |    0.56328 |   39  |  &#10004;   |
|  MemberFactory.java  |  0.15967  |   0.11043  |    <span style="color:green">-0.04924</span> |     1.0 |    0.0  |  0.0005614023  |   0.0004876878  |    2.14459 |   3  |  &#10004;   |
|  ObjectPropertiesDialog.java  |  0.08601  |   0.05632  |    <span style="color:green">-0.02968</span> |     1.0 |    0.0  |  0.0002358754  |   0.0001011781  |    2.28086 |   3  |  &#10004;   |
|  ParserDDL.java  |  0.08831  |   0.05764  |    <span style="color:green">-0.03066</span> |     1.0 |    0.0  |  0.0003490371  |   0.0001346227  |    1.96688 |   4  |  &#10004;   |
|  PcmlData.java  |  0.17786  |   0.11824  |    <span style="color:green">-0.05962</span> |     1.0 |    0.0  |  0.0009026377  |   0.0003327675  |    2.39291 |   3  |  &#10004;   |
|  PreferenceConstants.java  |  0.14626  |   0.10287  |    <span style="color:green">-0.04338</span> |     1.0 |    0.0  |  0.0005771497  |   0.0001954651  |    2.20169 |   3  |  &#10004;   |
|  PreserveAspectRatioParser.java  |  0.09964  |   0.06918  |    <span style="color:green">-0.03046</span> |     1.0 |    0.0  |  0.0004050004  |   0.0001369037  |    1.84587 |   4  |  &#10004;   |
|  Product.java  |  0.00467  |   0.00369  |    <span style="color:green">-0.00098</span> |     1.0 |    0.0  |  2.3402e-06  |   1.162e-07  |    0.88299 |   16  |  &#10004;   |
|  QuickFixProcessor.java  |  0.11442  |   0.0782  |    <span style="color:green">-0.03622</span> |     1.0 |    0.0  |  0.0007063138  |   0.000314206  |    1.59941 |   5  |  &#10004;   |
|  RDResumeHandler.java  |  0.2038  |   0.12696  |    <span style="color:green">-0.07684</span> |     1.0 |    0.0  |  0.0046721297  |   0.0003312732  |    1.53249 |   6  |  &#10004;   |
|  ReportColonyPanel.java  |  0.18529  |   0.14693  |    <span style="color:green">-0.03836</span> |     1.0 |    0.0  |  0.0072231644  |   0.0012144706  |    0.5891 |   36  |  &#10004;   |
|  SimpleMapGenerator.java  |  0.14783  |   0.1593  |    <span style="color:red">+0.01147</span> |     0.01399 |    0.71123  |  0.0006057344  |   0.0047802196  |    0.22056 |   254  |  &#x274C;   |
|  SybaseASE15Dialect.java  |  0.04009  |   0.03062  |    <span style="color:green">-0.00947</span> |     1.0 |    0.0  |  0.0001194656  |   6.58433e-05  |    0.98174 |   13  |  &#10004;   |
|  TheOriginalJDTParserClass.java  |  0.07334  |   0.05024  |    <span style="color:green">-0.0231</span> |     1.0 |    0.0  |  0.0004579699  |   0.0001591374  |    1.31199 |   7  |  &#10004;   |
|  TriMeshBeveler.java  |  0.19965  |   0.13756  |    <span style="color:green">-0.06209</span> |     1.0 |    0.0  |  0.0009816282  |   0.0003004609  |    2.44605 |   3  |  &#10004;   |
|  TryStatement.java  |  0.13027  |   0.09031  |    <span style="color:green">-0.03997</span> |     1.0 |    0.0  |  0.0006201314  |   0.0002257321  |    1.93856 |   4  |  &#10004;   |
|  ULocale.java  |  0.12798  |   0.07983  |    <span style="color:green">-0.04815</span> |     1.0 |    0.0  |  0.0046365029  |   0.0002052152  |    0.97621 |   13  |  &#10004;   |
|  UnicodeSet.java  |  0.00153  |   0.00029  |    <span style="color:green">-0.00124</span> |     1.0 |    0.0  |  4.7689e-06  |   1.194e-07  |    0.79369 |   20  |  &#10004;   |
|  User.java  |  0.30254  |   0.21825  |    <span style="color:green">-0.08429</span> |     1.0 |    0.0  |  0.0017428741  |   0.0003925647  |    2.57299 |   2  |  &#10004;   |
|  VPayment.java  |  0.13085  |   0.0908  |    <span style="color:green">-0.04004</span> |     1.0 |    0.0  |  0.0005595854  |   0.0001934823  |    2.05853 |   3  |  &#10004;   |

**Comment by KatGarmash** [comment]
@EvgeniyMaslov for how many files was the difference significant?

**Comment by KatGarmash** [comment]
@lyriccoder @EvgeniyMaslov how many samples per file+model_version did u generate?

**Comment by KatGarmash** [comment]
@lyriccoder can u please add a readme explaining the logic of ur test

**Review by acheshkov — APPROVED** [review]

**Review by acheshkov — APPROVED** [review]

**Pull request merged**
